name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5  # 你可以换成适合你的 Gradle 版本

    - name: Regenerate Gradle Wrapper
      working-directory: NavidromeMusicPlayer
      run: |
        echo "gradlew versiong is:"
        ./gradlew --version
        echo "downgrade to use version 8.5"
        ./gradlew wrapper --gradle-version 8.5

    - name: Build with Gradle
      working-directory: NavidromeMusicPlayer
      run: |
        echo now directory
        pwd
        echo "list files"
        ls
        echo "start build..."
        ./gradlew assembleDebug
