name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fix line endings for gradlew
        run: sed -i 's/\r$//' gradlew

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Regenerate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 8.5

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build
